Document: avrdude
Title: Debian avrdude Manual
Author: <insert document author here>
Abstract: This manual describes what avrdude is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/avrdude/avrdude.sgml.gz

Format: postscript
Files: /usr/share/doc/avrdude/avrdude.ps.gz

Format: text
Files: /usr/share/doc/avrdude/avrdude.text.gz

Format: HTML
Index: /usr/share/doc/avrdude/html/index.html
Files: /usr/share/doc/avrdude/html/*.html
